### ISSUE TITLE
Old files can remain in release folder after roger release

### ISSUE THREAD

**Issue by hkrutzer** [DigitPaint/roger#56]
If git hash hasn't changed, files that were in the release and are no longer there after a second release, will still be in the release folder.

**Comment by edwinvdgraaf** [comment]
Thanks for your bug report, as we found out yesterday offline the issue seems to be on how for example https://github.com/DigitPaint/roger_themes/blob/master/lib/roger_themes/xc_finalizer.rb zips. It should remove the existing zip, otherwise it will may append files to the existing archive.

While we could add a check for [git-clean](https://git-scm.com/docs/git-clean) and [git-status](https://git-scm.com/docs/git-status) when release, it didn't appear this was the issue per se. 

Closing this for now but feel free to add additional comments or remark it case you believe this issue should be resolved in roger. :confetti_ball:
